//GET all GeoTags
GET http://localhost:3000/api/geotags
Accept: application/json
###

//POST one GeoTag
POST http://localhost:3000/api/geotags
Content-Type: application/json

{
  "name":"test",
  "latitude":"51",
  "longitude":"52",
  "hashtag":"#test"
}
###

//GET one GeoTag, insert Location header for /api/geotags/Castle
GET http://localhost:3000/api/geotags/Castle
Accept: application/json
###

//GET all GeoTags filtered with searchterm
GET http://localhost:3000/api/geotags?searchterm=Building
###

//GET all GeoTags filtered with location. All GeoTags inside the radius of this location
GET http://localhost:3000/api/geotags?latitude=49.15528&longitude=8.62126
###

//GET all GeoTags filtered with searchterm AND location
GET http://localhost:3000/api/geotags?searchterm=Building&latitude=49.15528&longitude=8.62126
###

//PUT change one GeoTag with name test to New Test. test is deleted and New Test is inserted at the beginning
PUT http://localhost:3000/api/geotags/test
Content-Type: application/json

{
  "name":"NewTest",
  "latitude":"20",
  "longitude":"52",
  "hashtag":"#test"
}
###

//DELETE one GeoTag
DELETE http://localhost:3000/api/geotags/45abf08f-70a3-4c6b-a30e-e47bce7b6663
###
